In [57]:
import numpy as np
import pandas as pd


In [58]:
df = pd.DataFrame({'text':['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output':[1,1,0,0]})

In [59]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

## Bow

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [61]:
# fetch all unique word (Vocabulary)
bow = cv.fit_transform(df['text'])

In [62]:
# fetch all unique (Vocabulary) word and their index
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [64]:
cv.get_feature_names_out()

array(['campusx', 'comment', 'people', 'watch', 'write'], dtype=object)

In [50]:
# converting 1st two documant to vector. showing cv.vocabulary_ index wise frequency of this two document.
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [51]:
# test with new document like predection. check with "cv.vocabulary_ index"
cv.transform(['campusx watch and write comment']).toarray()

array([[1, 1, 0, 1, 1]])

In [55]:
# this word of document are not present in dictionary. so all values frequency are zero.
# and this array dimension/shape will be equal to V (number of unique word in Corpus ).
# if new word come in test that not present in train data/V it will ignore and array dimension 
#will still be same as V
# it will check with all its vocabulary word to "test text". if present write frequency if not ignore it.
cv.transform(['Hello Arafat, how are you? can you here me']).toarray()

array([[0, 0, 0, 0, 0]])

In [53]:
print(bow.toarray())

[[1 0 1 1 0]
 [2 0 0 1 0]
 [0 1 1 0 1]
 [1 1 0 0 1]]


#### Twist with CountVectorizer

In [96]:
cv2 = CountVectorizer(analyzer='word', ngram_range=(1,3), max_features=20)
bow2 = cv2.fit_transform(df['text'])

In [103]:
len(cv2.get_feature_names_out())

15

In [100]:
cv2.get_feature_names_out()


array(['campusx', 'campusx watch', 'campusx watch campusx',
       'campusx write', 'campusx write comment', 'comment', 'people',
       'people watch', 'people watch campusx', 'people write',
       'people write comment', 'watch', 'watch campusx', 'write',
       'write comment'], dtype=object)

In [83]:
bow2.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

## TF-IDF

In [104]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [106]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()

In [109]:
tfidf = tf.fit_transform(df['text']).toarray()

In [110]:
tfidf 

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [111]:
tf.get_feature_names_out()

array(['campusx', 'comment', 'people', 'watch', 'write'], dtype=object)

In [119]:
tf.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [120]:
tf.transform(['Hello arafat write']).toarray()

array([[0., 0., 0., 0., 1.]])

In [123]:
# IDF for each word
print(tf.idf_)
print(tf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
